### ISSUE TITLE
.malabar_mode/classpath fails to be created on first run with maven 3.1.1 on Windows 7

### ISSUE THREAD

**Issue by jackcviers** [m0smith/malabar-mode#128]
On first run, .malabar_mode/classpath is not created. To fix it, you have to run `mvn -X -U -f ~/.emacs.d/elpa/malabar-mode-<version>/pom\classpath-3.1.1.pom`, then move `C:\Users\<username>\.malabar_mode\` to `C:\Users\<username>\AppData\.malabar_mode`. After that, malabar-mode runs perfectly.

The code for the workaround is the exact code that gets run in `malabar-groovy-make-class-path` in [groovy.el#172](https://github.com/m0smith/malabar-mode/blob/develop/src/main/lisp/malabar-groovy.el#L172) if the config file does not exist. I do not know why it writes the config to the incorrect location on win7. My malabar settings have `~/.malabar_mode/classpath` set as the config classpath file location, and `(expand-file-name "~")` expands to `c:/Users/jviers/AppData/Roaming`.

**Comment by m0smith** [comment]
The classpath is no longer needs as part of 2.0
