### ISSUE TITLE
Have to install every time I run emacs?

### ISSUE THREAD

**Issue by ProjectMoon** [m0smith/malabar-mode#130]
I installed malabar-mode from the package manager, and it says it's installed. However, none of the commands are available unless I force reinstall it every time I open emacs. Putting (require 'malabar-mode) in the init file doesn't work either as it just says it cannot find the package. I'm using emacs 24.3.1 on Linux Mint.

**Comment by dgutov** [comment]
This probably describes the why: http://stackoverflow.com/questions/11127109/emacs-24-package-system-initialization-problems

So I'd say it's problematic to just recommend users to put `(require 'malabar-mode)` in their init file.

**Comment by m0smith** [comment]
Thanks I will update the instructions


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Dmitry Gutov <notifications@github.com> </div><div>Date:01/04/2015  5:12 AM  (GMT-07:00) </div><div>To: m0smith/malabar-mode <malabar-mode@noreply.github.com> </div><div>Subject: Re: [malabar-mode] Have to install every time I run emacs? (#130) </div><div>
</div>This probably describes the why: http://stackoverflow.com/questions/11127109/emacs-24-package-system-initialization-problems

So I'd say it's problematic to just recommend users to put (require 'malabar-mode) in their init file.

**Comment by m0smith** [comment]
http://www.gnu.org/software/emacs/manual/html_node/elisp/Packaging-Basics.html#Packaging-Basics

**Comment by m0smith** [comment]
Fixed in develop
