### ISSUE TITLE
Error: Can't find library malabar

### ISSUE THREAD

**Issue by usharf** [m0smith/malabar-mode#141]
I've got every thing setup and the markers JVM-Java appears when openeing a Java file, w/o any errors, but non of the shortcuts/function seem to work or exist. When I try to invoke interactively functions like `malabar-version', I get and error "Can't find library malabar". 

```shell
find-library-name: Can't find library malabar
```

In other cases, when attempting to invoke tests, I see:
```shell
malabar-run-test: Wrong type argument: integer-or-marker-p, nil
```

**Comment by m0smith** [comment]
Thanks.  I will look into it. 


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Uri Sharf <notifications@github.com> </div><div>Date:01/05/2015  4:34 AM  (GMT-07:00) </div><div>To: m0smith/malabar-mode <malabar-mode@noreply.github.com> </div><div>Subject: [malabar-mode] Error: Can't find library malabar (#141) </div><div>
</div>I've got every thing setup and the markers JVM-Java appears when openeing a Java file, w/o any errors, but non of the shortcuts/function seem to work or exist. When I try to invoke interactively functions like `malabar-version', I get and error "Can't find library malabar".

find-library-name: Can't find library malabar
In other cases, when attempting to invoke tests, I see:

malabar-run-test: Wrong type argument: integer-or-marker-p, nil

**Comment by m0smith** [comment]
I found the problem with `malabar-version` and it will be fixed with the next release.

Please post a backtace of the `malabar-run-test` . I think I found the problem but I want ot make sure it is the same problem you are seeing.

**Comment by usharf** [comment]
I've changed my setup and enabled semantic manually. When I enable malabar-mode and then run `malabar-run-test`, I'm seeing:

```emacs-lisp
alabar-mode-body: Wrong type argument: stringp, nil
Idle Service Error semantic-idle-local-symbol-highlight-idle-function: "#<buffer QuizActivity.java> - Wrong type argume\
nt: arrayp, nil"
Contacting host: localhost:4428
malabar-run-test: Wrong type argument: integer-or-marker-p, nil
Idle Service Error semantic-idle-local-symbol-highlight-idle-function: "#<buffer QuizActivity.java> - Wrong type argume\
nt: arrayp, nil"
malabar-run-test: Wrong type argument: stringp, nil
Mark set
````

**Comment by m0smith** [comment]
I just pushed a new release.  If it does not clear up all these isues, open a new issue and post a backtrace if possible.  I've not see the semantic-idle problem at all so I am not sure of its origin.
