### ISSUE TITLE
Required feature `semantic/wisent/wisent' was not provided (test error in emacs 23.2.1, with CEDET from CVS HEAD)

### ISSUE THREAD

**Issue by stepb** [m0smith/malabar-mode#28]
I'm trying to build malabar from master.
The build gets as far as run-elisp-tests then fails with this output:
    [INFO] [exec:exec {execution: run-loadability-test}]
    [INFO] Setting up CEDET packages...
    [INFO] Setting up CEDET packages...done
    [INFO] Required feature `semantic/wisent/wisent' was not provided

I have CEDET built from CVS loading in my .emacs:
    (load-file "/usr/share/emacs/site-lisp/cedet/common/cedet.elc")

I know I have wisent because I can add the following to .emacs:
(require 'wisent)
But if I change it to: (require 'semantic/wisent/wisent) then it fails like the malabar build.

I have tested loading malabar major mode (from v1.3) in my emacs and it loads fine :)

I have to admit that I am new to emacs. I have just mastered the basics and I'm hoping to switch to using emacs as my IDE instead of Eclipse. I am a Java dev and don't know elisp.

**Comment by m0smith** [comment]
malabar is no longer using its own grammer as of 2.0
