### ISSUE TITLE
Maven Exited Abnormally

### ISSUE THREAD

**Issue by jterk** [m0smith/malabar-mode#56]
Hi, I'm having some trouble invoking maven from malabar mode.

I've followed the directions in the README to install malabar mode and, superficially anyways, everything seems to be working.

I created a simple Maven project using `mvn archetype:generate` and chosing `maven-archetype-quickstart`. I then navigated to `App.java` (in `src/main/java`) and invoked C-c C-v C-b to run `mvn install`. The compilation fails with an 'exited abnormally' error:

    Projects.get('/Users/jterk/Projects/simple-maven-project/pom.xml', []).run(['install'], [], [:])
    [INFO] Scanning for projects...
    [INFO] ------------------------------------------------------------------------
    [INFO] Building SimpleProject 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ SimpleProject ---
    [WARNING] The POM for org.apache.maven.shared:maven-filtering:jar:1.0-beta-4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 0.403s
    [INFO] Finished at: Tue Jan 04 20:50:04 EST 2011
    [INFO] Final Memory: 50M/115M
    [INFO] ------------------------------------------------------------------------
    
    Compilation exited abnormally at Tue Jan  4 20:50:04

If I invoke Maven from the command line everything works as expected:

    > mvn install
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building SimpleProject 1.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ SimpleProject ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /Users/jterk/Projects/simple-maven-project/src/main/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ SimpleProject ---
    [INFO] Compiling 1 source file to /Users/jterk/Projects/simple-maven-project/target/classes
    [INFO] 
    [INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ SimpleProject ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /Users/jterk/Projects/simple-maven-project/src/test/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ SimpleProject ---
    [INFO] Compiling 1 source file to /Users/jterk/Projects/simple-maven-project/target/test-classes
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.5:test (default-test) @ SimpleProject ---
    [INFO] Surefire report directory: /Users/jterk/Projects/simple-maven-project/target/surefire-reports
    
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running com.goterkyourself.AppTest
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
    
    Results :
    
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
    
    [INFO] 
    [INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ SimpleProject ---
    [INFO] Building jar: /Users/jterk/Projects/simple-maven-project/target/SimpleProject-1.0-SNAPSHOT.jar
    [INFO] 
    [INFO] --- maven-install-plugin:2.3.1:install (default-install) @ SimpleProject ---
    [INFO] Installing /Users/jterk/Projects/simple-maven-project/target/SimpleProject-1.0-SNAPSHOT.jar to /Users/jterk/.m2/repository/com/goterkyourself/SimpleProject/1.0-SNAPSHOT/SimpleProject-1.0-SNAPSHOT.jar
    [INFO] Installing /Users/jterk/Projects/simple-maven-project/pom.xml to /Users/jterk/.m2/repository/com/goterkyourself/SimpleProject/1.0-SNAPSHOT/SimpleProject-1.0-SNAPSHOT.pom
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.738s
    [INFO] Finished at: Tue Jan 04 20:55:05 EST 2011
    [INFO] Final Memory: 12M/81M
    [INFO] ------------------------------------------------------------------------

What do I need to configure to get Maven to work when invoked from malabar-mode?

**Comment by m0smith** [comment]
Should be fixed in 2.0
