### ISSUE TITLE
Error on mvn package -- Symbol's function definition is void: eieio-defclass-autoload

### ISSUE THREAD

**Issue by jetaggart** [m0smith/malabar-mode#58]
Hey there-

I am trying to build malabar on Ubuntu 10.10 using GNU Emacs 23.2 with built in CEDET. I get an error upon emacs trying to execute load-all.el. It seems like an issue with semantic, but I'm not sure.

Here is the full output:
<pre>
[INFO] [exec:exec {execution: run-elisp-tests}]
[INFO] Loading /home/psylinse/malabar-mode/src/test/lisp/malabar-util.elk...
[INFO] [exec:exec {execution: run-loadability-test}]
[INFO] "/usr/share/emacs/23.2/site-lisp/cedet-common/" added to `load-path'
[INFO] Setting up cedet...
[INFO] Setting up cedet...done
[INFO] Setting up cogre...
[INFO] Setting up cogre...done
[INFO] Setting up ede...
[INFO] Loading `eieio': old-style backquotes detected!
[INFO] Loading vc-git...
[INFO] Setting up ede...done
[INFO] Setting up eieio...
[INFO] Setting up eieio...done
[INFO] Setting up semantic...
[INFO] Setting up semantic...done
[INFO] Setting up speedbar...
[INFO] Setting up speedbar...done
[INFO] Setting up cedet-contrib...
[INFO] Setting up cedet-contrib...done
[INFO] Symbol's function definition is void: eieio-defclass-autoload
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Result of /bin/sh -c cd /home/psylinse/malabar-mode && emacs -Q --batch -l src/test/lisp/load-all.el execution is: '255'.
</pre>

Any ideas? Thanks!

**Comment by m0smith** [comment]
The cedet we are using does not appear to have this issue.
