### ISSUE TITLE
Semantic code completion fails on Emacs 23.2 Debian

### ISSUE THREAD

**Issue by guancio** [m0smith/malabar-mode#61]
When i invoke semantic-ia-complete-symbol the command fails printing semantic-analyze-scoped-inherited-tag-map: Wrong type argument: listp, ERROR.

I checked that malabar correctly fin the maven pom by invoking malabar-compile-file

**Comment by m0smith** [comment]
Version 2.0 seems to have fixed this problem.  

`semantic-ia-complete-symbol` is bound to `C-c C-v C-.`
