### ISSUE TITLE
malabar-groovy-eval shortens output

### ISSUE THREAD

**Issue by anwyn** [m0smith/malabar-mode#62]
malabar-groovy--eval-fix-output seems to strip one character to many af the end of the output.

See:
https://github.com/espenhw/malabar-mode/blob/master/src/main/lisp/malabar-groovy.el#L309
shouldn't this be

    (substring output (match-end 0))

I see this on Linux, in case that this is a line ending issue.

Example:

    (cdr (malabar-groovy-eval
            (concat (malabar-project-classpath (current-buffer))
                    ".asClassPath();")))

cuts the 'r' from last jar in the classpath.

**Comment by m0smith** [comment]
THis Function no Longer exists
