### ISSUE TITLE
Malabar Mode is Coupled to a Maven (Version)

### ISSUE THREAD

**Issue by r351574nc3** [m0smith/malabar-mode#85]
With each subsequent version of Maven, a new malabar-mode build needs to be tagged. This couples a maven version to malabar-mode. 

I'm running into an issue right now where my current maven installation is ignored when compiling my project. Instead, a different maven version is being used. I would like my current maven installation to be used. 

Maybe malabar-mode should build by creating a subproject from archetype and building that. This would allow you dynamic builds based on the current installed version of maven. That is using an archetype, it would be possible to inherently know the maven build and appropriately build malabar-mode for that maven version without interaction.

Another option would be to determine my maven version via MAVEN_HOME and use that for building instead of bundling with malabar-mode.

**Comment by m0smith** [comment]
Fixed with the rewrite
